[build]
  publish = "dist"
  command = "yarn build"

[context.production.environment]
  APP_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "https://montuno.club/*"
  to = "https://wedance.vip/MontunoClub/:splat"
  status = 200
  force = true
