services:
  wedance-bot:
    build: .
    volumes:
      - ../:/usr/src/app/
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - wedance-bot-network
  wedance-bot-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ../:/usr/src/app/
    env_file:
      - .env
    networks:
      - wedance-bot-network
    command: npm run dev
networks:
  wedance-bot-network:
    driver: bridge
